### ISSUE TITLE
Consumer latency grows with consumer count

### ISSUE THREAD

**Issue by apeloquin-agilysys** [confluentinc/confluent-kafka-javascript#124] opened 2024-10-17 01:19 UTC
Our application interacts with dozens of topics.  As we've been transitioning functionality bit-by-bit to using Confluent, we've noticed an unfortunate increase in consumer latency.  

I was finally able to replicate the issue outside of our application.  The scenario is having multiple consumers but only sending messages to one of them (or a small subset).  When messages are round-robin'd to all present consumers this behavior does not occur.  Using KafkaJS running the same scenario, this behavior does not occur.

I'm hoping there is a configuration-driven solution to this problem, but I was unable to determine one on my own.   

```typescript
import {KafkaJS as Confluent, RdKafka} from "@confluentinc/kafka-javascript";
import {fail} from "assert";

const groupId = (t: number) => `test-confluent-group-${t}`;
const topic = (t: number) => `test-confluent-topic-${t}`;

describe("Consumer latency", () => {
  let kafka: Confluent.Kafka;
  let admin: Confluent.Admin;
  let producer: Confluent.Producer;
  let consumers: Confluent.Consumer[] = [];
  let consumersReady = new Set<number>();
  let messagesReceived: string[] = [];

  beforeEach(async () => {
    consumers = [];
    consumersReady.clear();

    kafka = new Confluent.Kafka({kafkaJS: {brokers: ["localhost:9092"]}});
    admin = kafka.admin();
    await admin.connect();
  });

  afterEach(async () => {
    const promises: Promise<void>[] = [];
    promises.push(admin.disconnect());
    promises.push(producer.disconnect());
    for (const consumer of consumers) {
      promises.push(consumer.disconnect());
    }
    await Promise.all(promises);
  });

  it("with 1 topic & consumer", async () => {
    await runTest(1, 16);
  });

  it("with 2 topics & consumers", async () => {
    await runTest(2, 16);
  });

  it("with 4 topics & consumers", async () => {
    await runTest(4, 16);
  });

  it("with 8 topics & consumers", async () => {
    await runTest(8, 16);
  });

  it("with 16 topics & consumers", async () => {
    await runTest(16, 16);
  });

  it("with 32 topics & consumers", async () => {
    await runTest(32, 16);
  });

  async function runTest(topicCount: number, messageCount: number) {
    // clear all groupIds to avoid contamination from previous runs
    const groupIds: string[] = [];
    for (let t = 0; t < topicCount; t++) {
      groupIds.push(groupId(t));
    }
    await admin.deleteGroups(groupIds);

    // ensure topics exist
    const topics: Confluent.ITopicConfig[] = [];
    for (let t = 0; t < topicCount; t++) {
      topics.push({topic: topic(t)});
    }
    await admin.createTopics({topics});

    let promises: Promise<any>[] = [];
    for (let t = 0; t < topicCount; t++) {
      promises.push(setupConsumer(t, messageCount));
    }
    await Promise.all(promises);

    producer = kafka.producer({"linger.ms": 0});
    await producer.connect();

    await until(() => consumersReady.size === topicCount);

    messagesReceived = [];

    promises = [];
    for (let m = 0; m < messageCount; m++) {
      const theTopic = topic(0);
      const headers = {created: new Date().toISOString()};
      const value = `Confluent Message ${m + 1}`;
      console.log(`[Sending] @ ${theTopic}: ${value}`);
      promises.push(producer.send({topic: theTopic, messages: [{headers, value}]}));
    }
    await Promise.all(promises);

    await until(() => messagesReceived.length === messageCount);
  }

  async function setupConsumer(t: number, messageCount: number) {
    let ready = false;
    const consumer = kafka.consumer({
      kafkaJS: {groupId: groupId(t), maxWaitTimeInMs: 100},
      rebalance_cb: (err: any, assignment: any, consumer: any) => {
        if (err.code !== RdKafka.CODES.ERRORS.ERR__ASSIGN_PARTITIONS) return;
        if (!ready) {
          ready = true;
          consumersReady.add(t);
        }
      }
    });
    await consumer.connect();
    await consumer.subscribe({topic: topic(t)});
    await consumer.run({
      eachMessage: async ({message}) => {
        const value = message.value?.toString() ?? "";
        messagesReceived.push(value);
        const delay = Date.now() - new Date(message.headers?.created as string).getTime();
        console.log(`[Received] @ ${topic(t)} (#${messagesReceived.length} of ${messageCount}): ${value} (${delay}ms)`);
      }
    });
    consumers.push(consumer);
  }

  async function until(condition: () => boolean) {
    const timeout = 60000;
    const finish = Date.now() + timeout;
    while (Date.now() <= finish) {
      const result = await condition();
      if (result) return;
      await new Promise(resolve => setTimeout(resolve, 50));
    }
    fail(`Failed within ${timeout!}ms`);
  }
});
```

With 1 topic results are consistent from the first to last message.
```console
[Received] @ test-confluent-topic-0 (#1 of 16): Confluent Message 1 (955ms)
...
[Received] @ test-confluent-topic-0 (#16 of 16): Confluent Message 16 (957ms)
```

With 2 and 4 topics, the results are similar.

As  we jump to 8 topics, the issue shows itself.  The 16th message takes an additional **4 seconds** to show up in the consumer.
```console
[Received] @ test-confluent-topic-0 (#1 of 16): Confluent Message 1 (1006ms)
...
[Received] @ test-confluent-topic-0 (#16 of 16): Confluent Message 16 (5019ms)
```

16 topics and now we have an additional **16 seconds**!
```console
[Received] @ test-confluent-topic-0 (#1 of 16): Confluent Message 1 (1004ms)
...
[Received] @ test-confluent-topic-0 (#16 of 16): Confluent Message 16 (17062ms)
```

32 topics, the test never completed its setup and was left in a hung state. 

Please help us find a path forward.

**Comment by milindl** [comment] 2024-10-22 06:56
Hey @apeloquin-agilysys , thanks for the great report. I've been able to reproduce this - I wanted to confirm one thing, in the actual production use case, are the consumers all running in the same node process just like this example? 

More context:

I don't quite have a complete answer yet but changing one of the internally (not yet exposed via the public interface) configurable parameters fixes the problem.

It seems that with the current settings, the event loop spends most of its time idling when there are consumers trying to fetch messages without availability of messages on their topics and this blocks the actual useful consumers. This isn't quite solved yet, since we need to work through the repercussions of changing the parameter (it might affect the throughput), and check if there is a better way.

**Comment by apeloquin-agilysys** [comment] 2024-10-22 14:28
Hi @milindl.  Thanks for the response.

> I wanted to confirm one thing, in the actual production use case, are the consumers all running in the same node process just like this example?

Yes, that is the case.  

> For a workaround based on environment variables, you can set UV_THREADPOOL_SIZE to a number greater than or equal to the number of consumers. 

I will try this out.

> we would ideally wish for this to be opaque to the user, or be able to work with just the default number of threads.

I agree!  With KafkaJS we were easily able to establish 100+ consumers (in tests) with the default configuration and negligible latency, would hope for similar flexibility with Confluent.

**Comment by apeloquin-agilysys** [comment] 2024-10-23 13:51
Hi @milindl.  I must be missing something.  Setting the `UV_THREADPOOL_SIZE` environment variable to `32` makes no difference in the performance of this test for me.

I added the following to the _beforeEach_ method to confirm the value:
```typescript
console.log(`UV_THREADPOOL_SIZE=${process.env.UV_THREADPOOL_SIZE}`);
```
Results from 16 topic test:
```console
UV_THREADPOOL_SIZE=32
...
[Received] @ test-confluent-topic-0 (#1 of 16): Confluent Message 1 (1004ms)
...
[Received] @ test-confluent-topic-0 (#16 of 16): Confluent Message 16 (18053ms)
```

**Comment by milindl** [comment] 2024-10-23 15:32
Thanks @apeloquin-agilysys . I'm running my test like this (I stripped out the type annotations). I'm on node v22 and on a WSL system with 8 logical cpus.

```
export UV_THREADPOOL_SIZE=32
node ../path/to/mocha.js --timeout 120000 filename.js
```
I'm getting all the consumers to pretty much finish < 1000 ms in all the cases (and when I unset the env variable, I get similar results to you).

Perhaps it's related to OS or node version, but that won't really help if that's the case. Given what worked for me and what my perf profiles looked like, I was pretty certain of the root cause but I'll think if it can be something else, too.

Would it be possible for you to take a performance profile of both the cases (with both values of `UV_THREADPOOL_SIZE`)?

For taking the profile:
While running only the 16 or 32 consumer one (whichever finishes on your system), I added this code:

```js
    console.profile();
    await until(() => messagesReceived.length === messageCount);
    console.profileEnd();
```

I then [used vscode to attach to the test process to grab a profile](https://code.visualstudio.com/docs/nodejs/profiling#_collecting-a-profile). (You might need to add a sleep somewhere before the tests start to attach the process). I think you can also take a similar profile with chrome if you don't use vscode.


(This doesn't capture 100% of the consume duration but it gets most of it, we're only really looking for a representative sample)

**Comment by apeloquin-agilysys** [comment] 2024-10-23 18:27
Hi @milindl.  The reason it wasn't working for me is the `UV_THREADPOOL_SIZE` must exist in the environment before _node_ is launched.  Setting the environment variable from within the _node_ app, or via `dotenv/config` (which we use for managing environment variables required by the app) makes the value available to _node_ but not apparently not _librdkafka_.  (Is it possible to feed the node `process.env` to _librdkafka_?)

With it set, the 32 consumer test messages are all at ~1s.  

That's the good news.  The bad news is that this is an unwieldy workaround since this setting must be effectively managed outside the application.  Looking forward to the real solution!

**Comment by milindl** [comment] 2024-10-24 03:43
@apeloquin-agilysys Thanks - while I agree the workaround isn't the best, the fact that it works for you too is some strong evidence that the root cause we were thinking of it correct. That's a relief. 

I'm not quite certain why it doesn't work when you set it from within node. Maybe by that time, libuv has already initialized its threadpool (libuv is one of the components used by node itself to run their event loop). But it's just a guess.

**Comment by milindl** [comment] 2024-11-07 03:57
Closing with #135  being released. Let me know if it persists.

**Closed by milindl** 2024-11-07 03:57 UTC
Labels: bug, fixed-present-in-next-release
